services:
  - type: web
    name: flask-app
    runtime: docker
    env: python
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
      - key: FLASK_ENV
        value: production